name: Deploy click2checkin Project

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup SSH agent
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.SERVER_IP }} << 'EOF'
          set -e

          # Mark the directory as safe to avoid Git dubious ownership error
          git config --global --add safe.directory /var/www/hotel-reservation

          # Navigate or clone repo
          if [ ! -d "/var/www/hotel-reservation" ]; then
            git clone https://github.com/Lprabodha/hotel-reservation /var/www/hotel-reservation
          fi

          cd /var/www/hotel-reservation
          git reset --hard
          git pull origin main

          # Composer install/update
          composer install --no-interaction --prefer-dist --optimize-autoloader

          # Run migrations
          php artisan migrate --force

          # Install Node.js dependencies and build assets
          npm install
          npm run prod

          # Set correct permissions (adjust user if needed)
          sudo chown -R www-data:www-data /var/www/hotel-reservation/storage /var/www/hotel-reservation/bootstrap/cache

          # Reload Nginx
          sudo systemctl reload nginx
        EOF
        echo "Deployment completed successfully!"
