name: Deploy click2checkin Project

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup SSH agent
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.SERVER_IP }} << 'EOF'
          set -e

          PROJECT_DIR="/var/www/hotel-reservation/"

          echo "Fixing ownership to avoid Git permission issues..."
          sudo chown -R ubuntu:ubuntu $PROJECT_DIR

          echo "Navigating to project directory: \$PROJECT_DIR"
          cd $PROJECT_DIR

          # Reset and pull latest changes
          echo "Pulling latest changes from main branch..."
          git reset --hard
          git pull origin main

          echo "Installing PHP dependencies..."
          composer install --no-interaction --prefer-dist --optimize-autoloader

          echo "Running database migrations & seeders..."
          php artisan migrate:fresh --seed --force

          echo "Fixing Laravel permissions..."
          sudo chown -R www-data:www-data storage bootstrap/cache
          sudo chmod -R 775 storage bootstrap/cache

          echo "Installing and building frontend assets..."
          # npm install
          # npm run build

          echo "✅ Deployment completed successfully!"
        EOF
